# Generated by Django 3.1.4 on 2020-12-06 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_content_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
