# Generated by Django 3.1.2 on 2020-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='portfolio',
            field=models.BooleanField(default=False),
        ),
    ]
