# Generated by Django 3.1.4 on 2020-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_replaced_category_with_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
